<?php

require_once dirname(dirname(__FILE__)).'/cloudMonitor.php';
require_once dirname(__FILE__).'/bootstrap.php';

/**
 * Test class for cloudMonitor.
 * Generated by PHPUnit on 2012-03-30 at 20:01:36.
 */
class cloudMonitorTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var cloudMonitor
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new cloudMonitor(API_USER, API_PASS);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testAuthenticate(){
        $this->assertTrue($this->object->authenticate(), 'test the auth function returns true');
        $this->assertTrue($this->object->isAuthenticated(), 'test the isAuth function returns true');


    }
 /**
     * @covers cloudMonitor::limits
     */
    public function testLimits(){
        $this->assertTrue(is_array($this->object->get_limits()), 'test the limits call returns an array');
    }

    /**
     * @covers cloudMonitor::set_cabundle
     * @todo Implement testSet_cabundle().
     */
    public function testSet_cabundle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers cloudMonitor::getLastResponseMessage
     * @todo Implement testGetLastResponseMessage().
     */
    public function testGetLastResponseMessage()
    {
       $this->assertTrue(is_array($this->object->get_limits()), 'test the limits call returns an array');
       $this->assertTrue($this->object->getLastResponseMessage() == 'Successful informational response', 'test the limits call returns an array');


    }

    /**
     * @covers cloudMonitor::getLastResponseStatus
     * @todo Implement testGetLastResponseStatus().
     */
    public function testGetLastResponseStatus()
    {
        $this->assertTrue(is_array($this->object->get_limits()), 'do a call to limits to as this is likly to return a 200');
        $this->assertTrue($this->object->getLastResponseStatus() == 200, 'test the limits call returns an array');

    }
}
?>
